jobs: 
  build: 
    machine: true
    steps: 
      - 
        run: 
          command: |
              cd ~
              git clone https://github.com/pradeep-tal/CitiDependent.git
              cd CitiDependent
              mvn -DskipTests clean install
          name: "git clone priavte project"
      - checkout
      - 
        restore_cache: 
          keys: 
            - "v1-dependencies-{{ checksum \"pom.xml\" }}"
            - v1-dependencies-
      - 
        run: 
          command: "mvn -DskipTests clean install dependency:resolve-plugins dependency:go-offline"
          name: "maven build"
      - 
        save_cache: 
          key: "v1-dependencies-{{ checksum \"pom.xml\" }}"
          paths: 
            - ~/.m2
      - 
        run: "docker login -u 8408 -p docker123"
      - 
        run: "docker build -t 8408/pd:citiapi ."
      - 
        run: "docker push 8408/pd:citiapi"
    working_directory: ~/repo
version: 2

