version: 2
jobs:
 build:
   machine: true
   steps:
     - checkout

      - run: |
         docker login -u pradeepdyapa@gmail.com -p docker123

     # build the application image
     - run: docker build -t pd/app:citiapi .

     # deploy the image
     - run: docker push pd/app:citiapi
