version: 2
jobs:
 build:
   machine: true

   working_directory: ~/repo
  
   steps:
    
     - checkout

     - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "pom.xml" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

     - run: 
       
        name: maven build 
        command: mvn -DskipTests clean install dependency:resolve-plugins dependency:go-offline
       
     - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}
     
     - run: docker login -u 8408 -p docker123

     # build the application image
     - run: docker build -t 8408/pd:citiapi .

     # deploy the image
     - run: docker push 8408/pd:citiapi
