version: 2
jobs:
 build:
   machine: true
   steps:
     - checkout

     - run: mvn -DskipTests clean install dependency:resolve-plugins dependency:go-offline
 
     - run: docker login -u 8408 -p docker123

     # build the application image
     - run: docker build -t 8408/pd:citiapi .

     # deploy the image
     - run: docker push 8408/pd:citiapi
